### ISSUE TITLE
Cannot destructure property 'ipv4Address' of 'data' as it is null

### ISSUE THREAD

**Issue by l4yl4** [orassayag/spam-revenge#1]
**What has happend:**
`npm start` leads to the following error:
```js
> spam-revenge@1.0.0 start
> node src/scripts/subscribe.script.js

===INITIATE THE SERVICES===
===VALIDATE GENERAL SETTINGS===
===INITIATE LOCAL DATA===
TypeError: Cannot destructure property 'ipv4Address' of 'data' as it is null.
    at new LocalDataModel (/home/user/Downloads/spam-revenge/src/core/models/files/LocalData.model.js:4:17)
    at LocalService.setLocalData (/home/user/Downloads/spam-revenge/src/services/files/local.service.js:12:31)
    at SubscribeLogic.validateSubscription (/home/user/Downloads/spam-revenge/src/logics/subscribe.logic.js:59:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SubscribeLogic.run (/home/user/Downloads/spam-revenge/src/logics/subscribe.logic.js:20:9)
    at async /home/user/Downloads/spam-revenge/src/scripts/subscribe.script.js:6:5
```

**Steps to reproduce:**
- Clone repository
- install dependencies `npm i`
- Add a valid mail address to `src/settings/settings.js`.
- Run application with `npm start`

**Additional information:**
- tried with node version v16.5.0
- changed *PUBLIC_IP_ADDRESS_URL* in `src/settings/settings.js` to different sites which return your IP
  - https://icanhazip.com
  - https://ifconfig.me

**Comment by orassayag** [comment]
Thanks, will fix it soon.
